name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      image_tag: | # add image tags here
        latest
        0.11.0-bullseye-r1 # renovate: datasource=github-releases depName=nginxinc/nginx-prometheus-exporter
        0.11.0-bullseye # renovate: datasource=github-releases depName=nginxinc/nginx-prometheus-exporter
        0.11.0 # renovate: datasource=github-releases depName=nginxinc/nginx-prometheus-exporter
        0.11
        0
    secrets: inherit
