name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      version: 0.11.0 # renovate: datasource=github-releases depName=nginxinc/nginx-prometheus-exporter
      latest: true
      major_only_tag: true
    secrets: inherit
